### ISSUE TITLE
cider-browse-ns not work

### ISSUE THREAD

**Issue by em7** [clojure-emacs/helm-cider#7] opened 2018-01-24 19:53 UTC
Hello, I've found an issue with helm-cider.

If I have helm-cider turned on, cider-browse-ns command doesn't work for me. When I turn off helm-cider, everything works as usual.

## Expected behavior

When I use `M-x cider-browse-ns` and select namespace, I expect list of vars in the namespace.

## Actual behavior

When I select a namespace from list, I got following error message in minibuffrer:

`helm-M-x: Wrong type argument: stringp, nil`

## Steps to reproduce the problem

- Open project.clj in Emacs
- Cider-jack-in
- Run cider-browse-ns
- Select a namespace from menu

### Helm

````
helm-cider 0.3.0
helm 2.8.7
````

### CIDER version information

````
;; CIDER 0.16.0 (Riga), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_152
````

### Lein/Boot version

`Leiningen 2.8.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM`

### Emacs version

`GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-26`

### Operating system

`Windows 7 64 bit`

(with latest updates)

**Comment by xiongtx** [comment] 2018-01-25 21:32
Cannot reproduce.

![helm-cider-jack-in](https://user-images.githubusercontent.com/1624090/35413349-fd971f3c-01d3-11e8-984a-9fa40d498c14.gif)

Try `cider-jack-in` again. Also try restarting Emacs. If the problem persists, link me to an example project and record a GIF of your steps.

**Comment by em7** [comment] 2018-01-26 15:10
Hello, I can show you on this project (it's a chapter from Clojure for Brave and True). This uses Clojure 1.8, the same version you used.

https://github.com/em7/mpegthing

![cider-browse-ns](https://user-images.githubusercontent.com/4933100/35445883-5ed1022e-02b3-11e8-8c81-0e87e2d80ab9.gif)

**Comment by xiongtx** [comment] 2018-01-27 03:08
Still cannot reproduce. Did you restart Emacs?

**Comment by xiongtx** [comment] 2018-01-31 00:40
Closing this for now. Feel free to reopen if you upgrade to latest versions and are still having trouble.

**Closed as completed by xiongtx** 2018-01-31 00:40 UTC

**Comment by xiongtx** [comment] 2018-01-31 19:20
From what I can figure out, this is likely b/c CIDER commands don't think you're connected to CIDER. E.g. try `(cider-var-info "clojure.core/=")` without jacking in. I'm not sure why it's happening if you've already jacked in, but a `cider-refresh` should solve it.

To improve error messages, I've made `helm-cider` actions that require CIDER verify that CIDER is connected. You should now see `<command> needs an active nREPL connection` instead of the more opaque `Wrong type argument: stringp, nil`.

**Comment by em7** [comment] 2018-02-03 09:08
Thanks, will try that.
